tap "nikitabobko/tap"

brew "nushell"
brew "neovim"
brew "lua-language-server"
brew "node"
brew "ripgrep"
brew "fd"
brew "typescript-language-server"
brew "vscode-langservers-extracted"
brew "tree-sitter-cli"
brew "jdtls"
brew "stylua"
brew "prettier"
brew "eslint_d"
brew "shfmt"
brew "shellcheck"
brew "black"
brew "ruff"
brew "go"
brew "goimports"
brew "rust"
brew "tmux"
brew "gitmux"
brew "oh-my-posh"
brew "carapace"
brew "lazygit"
brew "yazi"
brew "opencode"
cask "ghostty"
cask "hammerspoon"
cask "claude-code"
cask "visual-studio-code"
cask "nikitabobko/tap/aerospace"
cask "cmux"
brew "git"

# Optional: tmux plugin manager (TPM)
# brew "tmuxinator"
